### ISSUE TITLE
Criar pacote PyPI

### ISSUE THREAD

**Issue by staticdev** [thalesbertaglia/enelvo#12]
* Sugiro usar o Poetry e criar um pyproject.toml (ele veio com as PEP 517/518) para substituir o setup.py, MANIFEST, setup.cfg e requirements.txt).
* Alterar travis para usar poetry.

**Comment by staticdev** [comment]
@tfcbertaglia fiz um pull request #13 adicionando o poetry. Não removi os arquivos de setup e requirements para ser possível testar.

Para rodar local é só instalar o poetry:

```sh
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
source ~/.poetry/env
```

**Comment by staticdev** [comment]
Vi que o Travis quebrou, é porque o poetry gera um setup.py. No caso como já existe um, ele não sobrescreve e dá pau. Acho que o pyproject.toml já está fazendo o que o setup.py faz, ele poderia ser seguramente removido.

**Comment by staticdev** [comment]
@tfcbertaglia o Travis tá passando, muito bom. O próximo passo é criar uma conta no PyPI e gerar um token, ai se vc cadastrar como secret no Github, eu posso criar um Github action que publica como um pacote para você.

**Comment by thalesbertaglia** [comment]
Usei a action de um repo seu como exemplo e fiz uma, acho que tá ok.

**Comment by staticdev** [comment]
@thalesbertaglia massa demais, vi aqui. Vou testar e te mando email.
