### ISSUE TITLE
Problema com o módulo emoji

### ISSUE THREAD

**Issue by FerroEduardo** [thalesbertaglia/enelvo#136]
Ao fazer o import `from enelvo.normaliser import Normaliser`, esse erro é apresentado:
```
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji' (/home/eduar/.local/lib/python3.10/site-packages/emoji/__init__.py)
```
Imagino que seja devido ao módulo `emoji` que está na versão `2.2.0`. Instalar a versão `1.6.3` resolveu o problema.

Estou usando o Python 3.10.6+WSL e enelvo 0.13

**Comment by danielsenna** [comment]
Estou com o mesmo problema, tentei instalar a versão 1.6.3, mas o erro continua, será que é pq estou usando python 3.8.13?

**Comment by FerroEduardo** [comment]
> Estou com o mesmo problema, tentei instalar a versão 1.6.3, mas o erro continua, será que é pq estou usando python 3.8.13?

Dá uma conferida se a versão `1.6.3` está realmente instalada. Eu tive que desinstalar o módulo e depois instalar a versão `1.6.3`.

![emoji version](https://user-images.githubusercontent.com/47820549/220361401-8daef649-9490-4c8b-9476-9d04804c28ce.png)

**Comment by danielsenna** [comment]
Realmente, está me retornando a versão 2.2.0, mas fiz o seguinte (imagem abaixo) e não funcionou.. não sei muito sobre o assunto, você consegue identificar o erro? 
![image](https://user-images.githubusercontent.com/20702695/220417831-1ae734a0-15bb-473f-8706-cac89c9a6c84.png)

**Comment by FerroEduardo** [comment]
> Realmente, está me retornando a versão 2.2.0, mas fiz o seguinte (imagem abaixo) e não funcionou.. não sei muito sobre o assunto, você consegue identificar o erro? Achei que após importar enelvo, desinstalar o pacote emoji e instalar novamente na versão desejada funcionaria, mas parece que continua na versão 2.2.0. Agradeço desde já :) Ps.: Estou rodando num github codespace pelo vscode, versão do python 3.8.13. Na pior das hipótese continuo o projeto sem usar o enelvo normaliser mesmo ![image](https://user-images.githubusercontent.com/20702695/220417831-1ae734a0-15bb-473f-8706-cac89c9a6c84.png)

Tenta reiniciar o kernel do notebook

**Comment by danielsenna** [comment]
funcionou!!
