### ISSUE TITLE
pp_line variable error on force_list corrections

### ISSUE THREAD

**Issue by mblobao** [thalesbertaglia/enelvo#139]
Prezado

ao tentar rodar o programa utilizando uma lista de correção forçada, o programa levantou um erro na linha 124 do arquivo enelvo.normiliser.py

o método normalise da classe Normaliser (na linha 124) insere o objeto pp_line como sendo self.pp_line, porém, nenhum attributo pp_line foi setado na classe Normaliser.

testando aqui, apenas a remoção do "self." funcionou bem

Agradeço a atenção

**Comment by thalesbertaglia** [comment]
Valeu pelo aviso! Arrumei lá.
